---
# source: http://www.googlinux.com/creating-docker-container-using-ansible/index.html

- include: "docker.yml"

- name: create timescaledb container
  become: true
  docker_container:
    name: "{{ debian_docker_timescaledb.name }}"
    image: "{{ debian_docker_timescaledb.image }}"
    privileged: "{{ debian_docker_timescaledb.privileged }}"
    ports: "{{ debian_docker_timescaledb.ports }}"
    env: "{{ debian_docker_timescaledb.env }}"
    network_mode: host

- name: install postgresql client
  become: true
  apt:
    name: postgresql-client
    state: present

- name: install psycopg2
  become: true
  pip:
    executable: pip3
    name: psycopg2-binary

- name: ensure database exists
  become: true
  postgresql_db:
    login_host: "localhost"
    name: "{{ debian_timescaledb.database_name }}"
    owner: "{{ debian_timescaledb.database_owner }}"
    state: present
  tags: configure

- name: retrieve {{ debian_timescaledb.database_name }} database extensions
  become: true
  postgresql_query:
    login_host: "localhost"
    db: "{{ debian_timescaledb.database_name }}"
    query: "select extname from pg_extension"
  register: db_extenstions

- name: ensure timescaledb extension is present for database
  become: true
  when: "'timescaledb' not in (db_extenstions | json_query('query_result[*].extname'))"
  postgresql_query:
    login_host: "localhost"
    db: "{{ debian_timescaledb.database_name }}"
    query: "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE"
  tags: configure
